version: "3.4"

services:
  site:
    image: amidoneyet:local
    build:
      context: .
    container_name: amidoneyet
    volumes:
      - ./src:/app/src
      - ./assets:/app/assets
      - ./index.html:/app/index.html
      - ./package.json:/app/package.json
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    command: "server"
