version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01

    steps:
      - checkout

      - run:
          name: "Build container"
          command: docker-compose build

      - run:
          name: Check formatting
          command: docker-compose run --rm site lint
